
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: peace_development

  

 
  

test:
  <<: *default
  database: peace_test




production:
  <<: *default
  database: peace_production
  username: peace
  password: <%= ENV["PEACE_DATABASE_PASSWORD"] %>
